spring.datasource.url=jdbc:postgresql://localhost:5432/codbusters
spring.datasource.username=postgres
spring.datasource.password=1122
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect